# Path labels
bug:
  - files/*
type:wontfix:
  - WONTFIX
enhancement:
  - data/*
area:data:
  - data/*
type:documentation:
  - data/*
  - documentation/*
  - README.md
documentation:
  - mydocumentation
