# Path labels
bug:
  - files/*
type:wontfix:
  - WONTFIX
enhancement:
  - data/*
area:data:
  - data/*
type:documentation:
  - data/*
  - documentation/*
  - README.md
documentation:
  - mydocumentation
area:Book:
  files:
    - "SoftwareGuide/Latex/*.tex"
type:BookStyle:
  files:
    - "^Latex/[^/]*"
