name: "Pull Request Labeler"
<<<<<<< HEAD
on: [pull_request]
=======
on:
- pull_request_target
>>>>>>> origin/main

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@main
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labels.yml
