name: label pull request on title
on:
  pull_request:
    types: [opened, edited]

jobs:

  labeler:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install requirements
      run:
        pip install -Uq ghapi
        pip install pyyaml
        pip --version
        pip list
    - name: Label pull request
      run: python .github/scripts/pr_title_regex_labeler.py
      env:
        CONTEXT_GITHUB: ${{ toJson(github) }}
